import hashlib
import hmac
import json
import re
from datetime import datetime
from random import random
from time import time

try:
    from colorama import Fore, Style
except ImportError:

    class Dummy:
        def __getattr__(self, name):
            return ""

    Fore = Dummy()
    Style = Dummy()


# Generated by Gemini 2.5 Pro ↓
class CustomBase64:
    def __init__(self, alphabet):
        # Validate the alphabet
        if len(alphabet) != 64:
            raise ValueError("Alphabet must contain 64 characters")
        if len(set(alphabet)) != 64:
            raise ValueError("Alphabet cannot contain duplicate characters")

        self.alphabet = alphabet
        self.pad_char = "="
        # Create character-to-index mapping
        self.char_to_index = {char: idx for idx, char in enumerate(alphabet)}

    def encode(self, data):
        """Base64 encode data using custom alphabet"""
        if isinstance(data, str):
            data = data.encode("utf-8")

        result = []
        padding = 0

        # Process data in chunks of 3 bytes
        for i in range(0, len(data), 3):
            # Take 3 bytes, pad with 0 if necessary
            chunk = data[i : i + 3]
            if len(chunk) < 3:
                padding = 3 - len(chunk)
                chunk += b"\x00" * padding

            # Convert 3 bytes into four 6-bit values
            value = (chunk[0] << 16) | (chunk[1] << 8) | chunk[2]

            # Get characters from custom alphabet
            result.append(self.alphabet[(value >> 18) & 0x3F])
            result.append(self.alphabet[(value >> 12) & 0x3F])
            result.append(self.alphabet[(value >> 6) & 0x3F])
            result.append(self.alphabet[value & 0x3F])

        # Add padding characters
        if padding > 0:
            result[-padding:] = [self.pad_char] * padding

        return "".join(result)

    def decode(self, encoded_data):
        """Decode Base64 data using custom alphabet"""
        # Remove all whitespace
        encoded_data = re.sub(r"\s+", "", encoded_data)
        padding = encoded_data.count(self.pad_char)

        # Check encoded data validity
        if len(encoded_data) % 4 != 0:
            raise ValueError("Encoded data length must be a multiple of 4")

        # Handle padding
        data = encoded_data.rstrip(self.pad_char)
        result = []

        # Process in chunks of 4 characters
        for i in range(0, len(data), 4):
            chunk = data[i : i + 4]
            # Pad with last character if chunk is less than 4
            while len(chunk) < 4:
                chunk += chunk[-1] if chunk else self.alphabet[0]

            # Convert characters to indices
            try:
                values = [self.char_to_index[c] for c in chunk]
            except KeyError as e:
                raise ValueError(f"Encoded data contains invalid character: {e}")

            # Convert four 6-bit values into 3 bytes
            value = (values[0] << 18) | (values[1] << 12) | (values[2] << 6) | values[3]

            # Extract 3 bytes
            byte1 = (value >> 16) & 0xFF
            byte2 = (value >> 8) & 0xFF
            byte3 = value & 0xFF

            result.extend([byte1, byte2, byte3])

        # Remove extra bytes from padding
        if padding > 0:
            result = result[:-padding]

        # Return as bytes
        return bytes(result)


class JQueryUtil:
    def __init__(self, version):
        # Initialize counter to current millisecond timestamp
        self.counter = int(time() * 1000)
        self.callback_base = gen_jQuery(version)  # gen_jQuery only generates the prefix

    def get_callback_name(self):
        # Use current counter then increment
        name = f"{self.callback_base}_{self.counter}"
        self.counter += 1
        return name

    def get_timestamp(self):
        # Use current counter then increment
        ts = self.counter
        self.counter += 1
        return ts


def chr_iso8859_1(code):
    return bytes([code]).decode("iso-8859-1")


def unsigned_right_shift(num, shift):
    # For negative numbers, convert to unsigned 32-bit integer
    if num < 0:
        num += 1 << 32
    # Perform right shift
    return num >> shift


def str_to_int_list(a: str, b: bool) -> list[int]:
    c = len(a)
    v = []
    # Process 4 characters at a time
    for i in range(0, c, 4):
        # Get char codes for current and subsequent positions
        # Handle boundary: use 0 if out of range
        code1 = ord(a[i]) if i < c else 0
        code2 = ord(a[i + 1]) if (i + 1) < c else 0
        code3 = ord(a[i + 2]) if (i + 2) < c else 0
        code4 = ord(a[i + 3]) if (i + 3) < c else 0

        # Combine into an integer (simulating JS bitwise ops)
        combined = code1 | (code2 << 8) | (code3 << 16) | (code4 << 24)
        v.append(combined)

    # If b is True, append original string length to the end
    if b:
        v.append(c)

    return v


def int_list_to_str(a: list[int], b: bool) -> str:
    d = len(a)
    c = (d - 1) << 2  # Left shift 2 (multiply by 4)

    if b:
        m = a[d - 1]
        # Check if m is in valid range
        if m < c - 3 or m > c:
            return ""
        c = m

    # Process each element and convert back to chars
    processed = []
    for num in a:
        # Extract 4 bytes and convert to chars
        char1 = chr_iso8859_1(num & 0xFF)
        char2 = chr_iso8859_1(unsigned_right_shift(num, 8) & 0xFF)
        char3 = chr_iso8859_1(unsigned_right_shift(num, 16) & 0xFF)
        char4 = chr_iso8859_1(unsigned_right_shift(num, 24) & 0xFF)
        processed.append(char1 + char2 + char3 + char4)

    # Join and slice based on b parameter
    result = "".join(processed)
    return result[:c] if b else result


def xEncode(str_data: str, key: str) -> str:
    """
    Python implementation of the JavaScript xEncode function.
    """
    if not str_data:
        return ""

    v = str_to_int_list(str_data, True)
    k = str_to_int_list(key, False)

    # Pad key to length 4 if needed
    if len(k) < 4:
        k.extend([0] * (4 - len(k)))

    n = len(v) - 1
    if n < 0:
        return ""

    z = v[n]
    y = v[0]
    c = 0x9E3779B9

    # Python equivalent of Math.floor(6 + 52 / (n + 1))
    q = 6 + 52 // (n + 1)
    d = 0

    while q > 0:
        d = (d + c) & 0xFFFFFFFF
        e = (d >> 2) & 3

        for p in range(n):
            y = v[p + 1]
            m = (z >> 5) ^ (y << 2)
            m += ((y >> 3) ^ (z << 4)) ^ (d ^ y)
            m += k[(p & 3) ^ e] ^ z
            v[p] = (v[p] + m) & 0xFFFFFFFF
            z = v[p]

        y = v[0]
        m = (z >> 5) ^ (y << 2)
        m += ((y >> 3) ^ (z << 4)) ^ (d ^ y)
        m += k[(n & 3) ^ e] ^ z
        v[n] = (v[n] + m) & 0xFFFFFFFF
        z = v[n]

        q -= 1

    return int_list_to_str(v, False)


# Generated by Gemini 2.5 Pro ↑


def username_encrypt(username: str) -> str:
    """
    Encrypt username according to srun3k-new.html.
    Shift each ASCII code by +4 and prepend {SRUN3}\r\n.
    """
    username_crypto = ""
    for char in username:
        username_crypto += chr(ord(char) + 4)
    return "{SRUN3}\r\n" + username_crypto


def gen_jQuery(jQuery_version: str) -> str:
    return "jQuery" + re.sub(r"\D", "", jQuery_version) + str(random())[2:]


def password_encrypt(raw_password: str, token: str) -> str:
    return hmac.new(token.encode(), raw_password.encode(), hashlib.md5).hexdigest()


def gen_info(token: str, username: str, password: str, ip: str, ac_id: str) -> str:
    info = json.dumps(
        {
            "username": username,
            "password": password,
            "ip": ip,
            "acid": ac_id,
            "enc_ver": "srun_bx1",
        },
        separators=(",", ":"),
    )
    return "{SRBX1}" + CustomBase64(
        "LVoJPiCN2R8G90yg+hmFHuacZ1OWMnrsSTXkYpUq/3dlbfKwv6xztjI7DeBE45QA"
    ).encode(xEncode(info, token).encode("iso-8859-1"))


def gen_chksum(
    token: str,
    username: str,
    hmd5_password: str,
    ac_id: str,
    ip: str,
    n: str,
    type_: str,
    info: str,
) -> str:
    chkstr = (
        token
        + username
        + token
        + hmd5_password
        + token
        + ac_id
        + token
        + ip
        + token
        + n
        + token
        + type_
        + token
        + info
    )
    return hashlib.sha1(chkstr.encode()).hexdigest()


def show_data_usage(data: int) -> str:
    if data < 1024:
        return f"{data} Bytes"
    elif data < 1024 * 1024:
        return "%.2f KiB" % (data / 1024)
    elif data < 1024 * 1024 * 1024:
        return "%.2f MiB" % (data / 1024 / 1024)
    else:
        return "%.2f GiB" % (data / 1024 / 1024 / 1024)


def show_time_formatted(seconds: int) -> str:
    minutes = seconds // 60
    hours = minutes // 60
    days = hours // 24
    if minutes <= 0:
        return f"{seconds} Seconds"
    elif hours <= 0:
        return f"{minutes} Minutes {seconds % 60} Seconds"
    elif days <= 0:
        return f"{hours} Hours {minutes % 60} Minutes {seconds % 60} Seconds"
    else:
        return f"{days} Days {hours % 24} Hours {minutes % 60} Minutes {seconds % 60} Seconds"


def log_info(*msg: str):
    print(f"[{datetime.now().strftime('%H:%M:%S')}]", *msg)


def log_warning(*msg: str):
    print(
        Fore.YELLOW + f"[{datetime.now().strftime('%H:%M:%S')}]", *msg, Style.RESET_ALL
    )


def log_error(*msg: str):
    print(Fore.RED + f"[{datetime.now().strftime('%H:%M:%S')}]", *msg, Style.RESET_ALL)


def log_debug(*msg: str):
    print(Style.DIM + f"[{datetime.now().strftime('%H:%M:%S')}]", *msg, Style.RESET_ALL)


def log_custom(color: str, *msg: str):
    print(color + f"[{datetime.now().strftime('%H:%M:%S')}]", *msg, Style.RESET_ALL)
